// [!] script.js의 MOCK_PROJECT_DATA를 그대로 가져옵니다.
export const MOCK_PROJECT_DATA = [
    // (script.js에 있던 20개 샘플 데이터)
    { "id": "brianoleary15/Hands-On-Machine-Learning-with-ScikitLearn-and-TensorFlow", "name": "Hands-On-Machine-Learning-with-ScikitLearn-and-TensorFlow", "stars": "36" },
        { "id": "SeveredSurvival/ageron_handson-ml", "name": "ageron_handson-ml", "stars": "12" },
        { "id": "PacktWorkshops/The-Machine-Learning-Workshop", "name": "The-Machine-Learning-Workshop", "stars": "43" },
        { "id": "francomanca93/machine-learning-profesional-con-scikit-learn", "name": "machine-learning-profesional-con-scikit-learn", "stars": "30" },
        { "id": "interpss/DeepMachineLearning", "name": "DeepMachineLearning", "stars": "36" },
        { "id": "PacktPublishing/Machine-Learning-with-scikit-learn-Quick-Start-Guide", "name": "Machine-Learning-with-scikit-learn-Quick-Start-Guide", "stars": "35" },
        { "id": "JulianoLagana/deep-machine-learning", "name": "deep-machine-learning", "stars": "13" },
        { "id": "alx-tools/deep-learning-vagrant-machine", "name": "deep-learning-vagrant-machine", "stars": "38" },
        { "id": "carpentries-incubator/machine-learning-novice-sklearn", "name": "machine-learning-novice-sklearn", "stars": "28" },
        { "id": "Vikramank/Deep-Learning-", "name": "Deep-Learning-", "stars": "46" },
        { "id": "chenhaishun/Hands-on-Machine-Learning-2edition", "name": "Hands-on-Machine-Learning-2edition", "stars": "31" },
        { "id": "SciSharp/scikit-learn.net", "name": "scikit-learn.net", "stars": "39" },
        { "id": "deysuman/MachineLearningStocks", "name": "MachineLearningStocks", "stars": "19" },
        { "id": "SupaeroDataScience/deep-learning", "name": "deep-learning", "stars": "15" },
        { "id": "PacktPublishing/Fundamentals-of-Machine-Learning-with-scikit-learn", "name": "Fundamentals-of-Machine-Learning-with-scikit-learn", "stars": "16" },
        { "id": "Anubhavdevv/Awesome-Machine-Learning-Models", "name": "Awesome-Machine-Learning-Models", "stars": "34" },
        { "id": "jarvisqi/deep_learning", "name": "deep_learning", "stars": "31" },
        { "id": "nanxstats/deep-learning-recipes", "name": "deep-learning-recipes", "stars": "46" },
        { "id": "PacktPublishing/TensorFlow-Deep-Learning-Projects", "name": "TensorFlow-Deep-Learning-Projects", "stars": "46" },
        { "id": "dml-cth/deep-machine-learning", "name": "deep-machine-learning", "stars": "31" }
];

// [!] script.js의 MOCK_PROJECT_DETAILS를 그대로 가져옵니다.
export const MOCK_PROJECT_DETAILS = {
     "brianoleary15/Hands-On-Machine-Learning-with-ScikitLearn-and-TensorFlow": { title: "Hands-On-Machine-Learning-with-ScikitLearn-and-TensorFlow", author: "@brianoleary15", ai_summary: "O'Reilly 'Hands-on ML' 책 예제 코드 및 연습문제 풀이 포함.", tags: "AI/ML, Python, TensorFlow, Scikit-learn", stars: "36", forks: "20", license: "apache-2.0", repo_url: "https://github.com/brianoleary15/Hands-On-Machine-Learning-with-ScikitLearn-and-TensorFlow", readme_content: "This repository contains notebooks for the O'Reilly book 'Hands-on Machine Learning with Scikit-Learn, Keras & TensorFlow'.\n\n### Chapters Covered\n* Chapter 1: The Machine Learning Landscape\n* Chapter 2: End-to-End Machine Learning Project\n* ...\n" },
        "SeveredSurvival/ageron_handson-ml": { title: "ageron_handson-ml", author: "@SeveredSurvival", ai_summary: "Aurelien Geron의 인기 ML 서적 관련 코드 포크 또는 복사본.", tags: "AI/ML, Python, Tutorial", stars: "12", forks: "5", license: "apache-2.0", repo_url: "https://github.com/SeveredSurvival/ageron_handson-ml", readme_content: "Code related to the Hands-on ML book by Aurelien Geron.\n\n**Note:** May be slightly modified from the original." },
        "PacktWorkshops/The-Machine-Learning-Workshop": { title: "The-Machine-Learning-Workshop", author: "@PacktWorkshops", ai_summary: "Packt 출판사의 'The Machine Learning Workshop' 서적 코드 리포지토리.", tags: "AI/ML, Python, Workshop", stars: "43", forks: "15", license: "mit", repo_url: "https://github.com/PacktWorkshops/The-Machine-Learning-Workshop", readme_content: "Companion code for the Packt workshop book 'The Machine Learning Workshop'.\n\nFocuses on practical applications and projects." },
        "francomanca93/machine-learning-profesional-con-scikit-learn": { title: "machine-learning-profesional-con-scikit-learn", author: "@francomanca93", ai_summary: "Scikit-learn을 사용한 전문 머신러닝 과정 관련 코드 (스페인어 추정).", tags: "AI/ML, Scikit-learn, Spanish", stars: "30", forks: "10", license: "mit", repo_url: "https://github.com/francomanca93/machine-learning-profesional-con-scikit-learn", readme_content: "Material del curso profesional de machine learning con scikit-learn.\n\nIncluye notebooks y ejemplos prácticos." },
        "interpss/DeepMachineLearning": { title: "DeepMachineLearning", author: "@interpss", ai_summary: "전력 시스템(InterPSS)과 관련된 딥러닝 프로젝트.", tags: "AI/ML, Power Systems", stars: "36", forks: "12", license: "apache-2.0", repo_url: "https://github.com/interpss/DeepMachineLearning", readme_content: "Using deep learning for power system analysis and simulation.\n\nIntegration with InterPSS library." },
        "PacktPublishing/Machine-Learning-with-scikit-learn-Quick-Start-Guide": { title: "Machine-Learning-with-scikit-learn-Quick-Start-Guide", author: "@PacktPublishing", ai_summary: "Packt의 'Machine Learning with scikit-learn Quick Start Guide' 서적 코드.", tags: "AI/ML, Scikit-learn, Guide", stars: "35", forks: "25", license: "mit", repo_url: "https://github.com/PacktPublishing/Machine-Learning-with-scikit-learn-Quick-Start-Guide", readme_content: "Code examples from the Quick Start Guide for scikit-learn.\n\nCovers basic models and techniques." },
        "JulianoLagana/deep-machine-learning": { title: "deep-machine-learning", author: "@JulianoLagana", ai_summary: "개인적인 딥러닝 프로젝트 또는 자료 모음.", tags: "AI/ML, Deep Learning", stars: "13", forks: "3", license: "mit", repo_url: "https://github.com/JulianoLagana/deep-machine-learning", readme_content: "Repository for deep machine learning explorations and experiments." },
        "alx-tools/deep-learning-vagrant-machine": { title: "deep-learning-vagrant-machine", author: "@alx-tools", ai_summary: "딥러닝 개발 환경 구성을 위한 Vagrant 설정.", tags: "AI/ML, Environment, Vagrant", stars: "38", forks: "8", license: "mit", repo_url: "https://github.com/alx-tools/deep-learning-vagrant-machine", readme_content: "Vagrant files to quickly set up a virtual machine with common deep learning libraries (TensorFlow, PyTorch, Keras)." },
        "carpentries-incubator/machine-learning-novice-sklearn": { title: "machine-learning-novice-sklearn", author: "@carpentries-incubator", ai_summary: "초심자를 위한 Scikit-learn 머신러닝 Carpentries 워크숍 자료.", tags: "AI/ML, Scikit-learn, Education", stars: "28", forks: "30", license: "cc-by-4.0", repo_url: "https://github.com/carpentries-incubator/machine-learning-novice-sklearn", readme_content: "Lesson materials for the Software Carpentry / Data Carpentry style workshop on novice machine learning with scikit-learn." },
        "Vikramank/Deep-Learning-": { title: "Deep-Learning-", author: "@Vikramank", ai_summary: "딥러닝 프로젝트 또는 학습 노트 모음.", tags: "AI/ML, Deep Learning", stars: "46", forks: "22", license: "mit", repo_url: "https://github.com/Vikramank/Deep-Learning-", readme_content: "Personal deep learning projects repository covering various topics and models." },
        "chenhaishun/Hands-on-Machine-Learning-2edition": { title: "Hands-on-Machine-Learning-2edition", author: "@chenhaishun", ai_summary: "'Hands-on Machine Learning' 서적 2판 관련 코드.", tags: "AI/ML, Python, TensorFlow", stars: "31", forks: "18", license: "apache-2.0", repo_url: "https://github.com/chenhaishun/Hands-on-Machine-Learning-2edition", readme_content: "Notebooks and code examples for the second edition of the popular book by Aurelien Geron." },
        "SciSharp/scikit-learn.net": { title: "scikit-learn.net", author: "@SciSharp", ai_summary: "인기 Python 라이브러리 Scikit-learn의 .NET 래퍼.", tags: "AI/ML, .NET, Scikit-learn", stars: "39", forks: "9", license: "mit", repo_url: "https://github.com/SciSharp/scikit-learn.net", readme_content: "Bringing scikit-learn functionality to the .NET ecosystem. Allows C# and F# developers to use familiar ML algorithms." },
        "deysuman/MachineLearningStocks": { title: "MachineLearningStocks", author: "@deysuman", ai_summary: "머신러닝 기술을 이용한 주식 시장 움직임 예측.", tags: "AI/ML, Finance, Stock Market", stars: "19", forks: "7", license: "mit", repo_url: "https://github.com/deysuman/MachineLearningStocks", readme_content: "Predicting stock prices using ML models based on historical data and fundamental analysis." },
        "SupaeroDataScience/deep-learning": { title: "deep-learning", author: "@SupaeroDataScience", ai_summary: "ISAE-Supaero의 딥러닝 과정 또는 프로젝트 관련 자료.", tags: "AI/ML, Education, Deep Learning", stars: "15", forks: "6", license: "mit", repo_url: "https://github.com/SupaeroDataScience/deep-learning", readme_content: "Deep learning course resources, including slides, notebooks, and assignments from ISAE-Supaero." },
        "PacktPublishing/Fundamentals-of-Machine-Learning-with-scikit-learn": { title: "Fundamentals-of-Machine-Learning-with-scikit-learn", author: "@PacktPublishing", ai_summary: "Packt 서적 'Fundamentals of Machine Learning with scikit-learn' 코드.", tags: "AI/ML, Python, Scikit-learn", stars: "16", forks: "8", license: "mit", repo_url: "https://github.com/PacktPublishing/Fundamentals-of-Machine-Learning-with-scikit-learn", readme_content: "Code examples covering ML fundamentals with scikit-learn, suitable for beginners." },
        "Anubhavdevv/Awesome-Machine-Learning-Models": { title: "Awesome-Machine-Learning-Models", author: "@Anubhavdevv", ai_summary: "다양한 머신러닝 모델의 큐레이션 목록 또는 컬렉션.", tags: "AI/ML, Awesome List", stars: "34", forks: "4", license: "mit", repo_url: "https://github.com/Anubhavdevv/Awesome-Machine-Learning-Models", readme_content: "Collection of awesome ML models and resources across different domains." },
        "jarvisqi/deep_learning": { title: "deep_learning", author: "@jarvisqi", ai_summary: "개인 딥러닝 학습 노트 또는 프로젝트 모음.", tags: "AI/ML, Deep Learning", stars: "31", forks: "9", license: "mit", repo_url: "https://github.com/jarvisqi/deep_learning", readme_content: "Repository documenting a personal deep learning journey and experiments." },
        "nanxstats/deep-learning-recipes": { title: "deep-learning-recipes", author: "@nanxstats", ai_summary: "딥러닝 작업을 위한 레시피 또는 코드 스니펫 모음.", tags: "AI/ML, PyTorch, Recipes", stars: "46", forks: "11", license: "mit", repo_url: "https://github.com/nanxstats/deep-learning-recipes", readme_content: "Useful code examples and recipes for common deep learning tasks using PyTorch." },
        "PacktPublishing/TensorFlow-Deep-Learning-Projects": { title: "TensorFlow-Deep-Learning-Projects", author: "@PacktPublishing", ai_summary: "Packt 서적 'TensorFlow Deep Learning Projects' 코드.", tags: "AI/ML, TensorFlow, Projects", stars: "46", forks: "20", license: "mit", repo_url: "https://github.com/PacktPublishing/TensorFlow-Deep-Learning-Projects", readme_content: "Hands-on projects using TensorFlow for implementing various deep learning models." },
        "dml-cth/deep-machine-learning": { title: "deep-machine-learning", author: "@dml-cth", ai_summary: "Chalmers 대학의 딥 머신러닝 자료 추정.", tags: "AI/ML, Education, Deep Learning", stars: "31", forks: "7", license: "mit", repo_url: "https://github.com/dml-cth/deep-machine-learning", readme_content: "Materials and resources for deep machine learning, possibly related to a course at Chalmers University." },
        'default': { title: "정보 없음", author: "@unknown", ai_summary: '상세 정보를 불러올 수 없습니다.', tags: '', stars: 'N/A', forks: 'N/A', license: 'N/A', repo_url: '#', readme_content: 'README 정보를 불러올 수 없습니다.' }
    };